// client/src/components/intro/Intro.jsx
import React from "react";
import Title from "../../shared/title/Title";
import "./Intro.scss";

const Intro = () => {
  const items = [
    "About Us",
    "Videos",
    "Shop",
    "News & Articles",
    "Get in Touch",
  ];

  const word1 = "for";
  const word2 = "you";

  return (
    <div>
      <div class="title-nav">
        <Title />
        <ul>
          {items.map((item) => (
            <li>{item.toUpperCase()}</li>
          ))}
        </ul>
      </div>
      <div class="intro">
        <div class="intro__text">
          <span>{word1.toUpperCase()}</span>
          <span>{word2.toLowerCase()}</span>
        </div>
      </div>
    </div>
  );
};

export default Intro;

// client/src/components/intro/intro.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-intro',
  templateUrl: './intro.component.html',
  styleUrls: ['./intro.component.scss'],
})
export class IntroComponent implements OnInit {
  constructor() {}

  items: string[] = [
    'About Us',
    'Videos',
    'Shop',
    'News & Articles',
    'Get in Touch',
  ];

  word1 = 'for';
  word2 = 'you';

  ngOnInit(): void {}
}

<div class="title-nav">
  <app-title></app-title>
  <ul>
    <li *ngFor="let item of items">{{ item | uppercase }}</li>
  </ul>
</div>
<div class="intro">
  <div class="intro__text">
    <span>{{ word1 | uppercase }}</span>
    <span>{{ word2 | uppercase }}</span>
  </div>
  <!-- <app-button content="<span>hello!</span>"></app-button> -->
</div>
